# Generated by Django 4.2.5 on 2023-09-21 14:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('isOrginalAllowed', models.BooleanField()),
                ('isExpiringAllowed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ThumbNail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxHeight', models.IntegerField(help_text='Stores the maximum possible value of the image', validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(200)])),
                ('tier', models.ForeignKey(help_text='Selected tier associated with this user account.', on_delete=django.db.models.deletion.CASCADE, to='api.tier')),
            ],
        ),
    ]
