# Generated by Django 4.2.5 on 2023-09-21 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_thumbnail_minheight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='minHeight',
            field=models.IntegerField(default=200, help_text='Stores the minimum possible value of the image', validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(200)]),
        ),
    ]
