# Generated by Django 4.2.5 on 2023-09-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_image_createdtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
    ]
