# Generated by Django 4.2.5 on 2023-09-23 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='isOrginalAllowed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tier',
        ),
        migrations.AddField(
            model_name='image',
            name='expiring_link_duration',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='image',
            name='original_image',
            field=models.ImageField(default=0, upload_to='originals/'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_200',
            field=models.ImageField(default=0, upload_to='thumbnails/200/'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_400',
            field=models.ImageField(default=0, upload_to='thumbnails/400/'),
        ),
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.tier'),
        ),
        migrations.DeleteModel(
            name='ThumbNail',
        ),
    ]
