# Generated by Django 4.0.4 on 2023-09-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_tier_isorginalallowed_remove_user_tier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='original_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_200',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_400',
        ),
        migrations.AddField(
            model_name='image',
            name='access_level',
            field=models.CharField(choices=[('basic', '(200)'), ('premium', '(200, 400)'), ('enterprise', '(200, 400, 1000)')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('basic', '(200)'), ('premium', '(200, 400)'), ('enterprise', '(200, 400, 1000)')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tier'),
        ),
    ]
