# Generated by Django 4.0.4 on 2023-09-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_image_original_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='access_level',
        ),
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('basic', 'Basic (200)'), ('premium', 'Premium (200)'), ('premium_400', 'Premium (400)'), ('enterprise', 'Enterprise (200)'), ('enterprise_400', 'Enterprise (400)'), ('enterprise_1000', 'Enterprise (1000)')], default=0, max_length=100),
        ),
    ]
