# Generated by Django 4.0.4 on 2023-09-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_image_access_level_alter_user_access_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_level',
        ),
        migrations.AddField(
            model_name='image',
            name='access_level',
            field=models.CharField(choices=[('basic', '200'), ('premium', '400'), ('enterprise', '1000')], default=1, max_length=100),
        ),
    ]
