# Generated by Django 4.0.4 on 2023-09-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_image_access_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='expiring_link_duration',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
